trigger:
  branches:
    include:
      - main  # Runs when code is pushed to `main`

pool:
  vmImage: 'ubuntu-latest'  # Runs on an Ubuntu agent

steps:
  # Step 1: Ensure Repository is Checked Out
  - checkout: self

  # Step 2: Verify Docker is Installed and Running
  - script: |
      docker --version
      docker info
    displayName: "Verify Docker Installation"

  # Step 3: Debug Environment Variables (if using Azure DevOps variables)
  - script: |
      env
    displayName: "Debug Environment Variables"

  # Step 4: Build Docker Image
  - script: |
      docker build -t sanjeevranahp/mke4:latest .
    displayName: "Build Docker Image"

  # Step 5: Log in to Docker Hub (Requires Service Connection)
  - script: |
      echo "$(DOCKERHUB_PASSWORD)" | docker login -u "$(DOCKERHUB_USERNAME)" --password-stdin
    displayName: "Docker Hub Login"

  # Step 6: Push Docker Image to Docker Hub
  - script: |
      docker push sanjeevranahp/mke4:latest
    displayName: "Push Image to Docker Hub"