trigger:
  branches:
    include:
      - main  # Runs when code is pushed to `main`

pool:
  vmImage: 'ubuntu-latest'  # Runs on an Ubuntu agent

steps:
  # Step 1: Ensure Repository is Checked Out
  - checkout: self

  # Step 2: Verify Docker is Installed and Running
  - script: |
      docker --version
      docker info
    displayName: "Verify Docker Installation"

  # Step 3: Debug Environment Variables (if using Azure DevOps variables)
  - script: |
      env
    displayName: "Debug Environment Variables"

  # Step 4: Build Docker Image
  - script: |
      set -x  # Enable debug mode
      docker build -t my-mke:latest .
    displayName: "Build Docker Image"

  # Step 5: Run Docker Container (with Debugging)
  - script: |
      docker stop my-mke-container || true
      docker rm my-mke-container || true
      docker images
      docker run -d --name my-mke-container my-mke:latest || docker logs my-mke-container
    displayName: "Run Docker Container & Debug Logs"