trigger:
  branches:
    include:
      - main  # Runs when code is pushed to `main`

pool:
  vmImage: 'ubuntu-latest'  # Runs on an Ubuntu agent

steps:
  - task: Checkout@1  # Pull the latest code from GitHub

  # Step 1: Build Docker Image
  - script: |
      docker build -t my-mke:latest .
    displayName: "Build Docker Image"

  # Step 2: Run Docker Container
  - script: |
      docker run -d --name my-mke-container my-mke:latest
    displayName: "Run Docker Container"